version: '3'

services:
  web-backend-api:
    build:
      context: backend/
      dockerfile: Dockerfile
    command: python backend/manage.py runserver
    volumes:
      - .:/code
    ports:
      - 8000:8000

  web-frontend-react:
    stdin_open: true
    build:
      context: frontend/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - web-backend-api