version: '3'
services:
#  DB:
#    image: postgres
#    environment:
#      - POSTGRES_DB=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
  web-backend-api:
    build:
      context: backend/
      dockerfile: Dockerfile
    command: python backend/manage.py runserver 127.0.0.1:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
#    depends_on:
#      - DB
  web-frontend-react:
    stdin_open: true
    build:
      context: frontend/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
#    volumes:
#      - "/app/node_modules"
#      - "./:/app"
    depends_on:
      - web-backend-api

